// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package season

import (
	"poketier/apps/season/internal/application/usecase"
	"poketier/apps/season/internal/infrastructure/repository"
	"poketier/apps/season/internal/presentation/handler"
	"poketier/sqlc/db"
)

// Injectors from di.go:

// InitializeListSeasonsHandler はListSeasonsHandlerとその依存関係を初期化します
func InitializeListSeasonsHandler(queries db.Querier) *handler.ListSeasonsHandler {
	seasonRepository := repository.NewSeasonRepository(queries)
	listSeasonsUsecase := usecase.NewListSeasonsUsecase(seasonRepository)
	listSeasonsHandler := handler.NewListSeasonsHandler(listSeasonsUsecase)
	return listSeasonsHandler
}
