services:
  poketier-backend:
    build:
      context: .
      dockerfile: build/Dockerfile_local
    container_name: poketier-backend
    networks:
      - poketier-network
    ports:
      - "28080:8080"  # アプリケーションポート
      - "22345:2345"  # Delveデバッガーポート
    volumes:
      - ./backend:/workspace
      - go-mod-cache:/go/pkg/mod
    environment:
      - CGO_ENABLED=0
    # コンテナを永続化（Delve・Goアプリは手動制御）
    command: ["/bin/sh", "-c", "while true; do sleep 30; done"]
    stdin_open: true
    tty: true

networks:
  poketier-network:
    driver: bridge

volumes:
  go-mod-cache: