// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BulkCreateSeasons(ctx context.Context, arg []BulkCreateSeasonsParams) (int64, error)
	// 指定したIDリストのシーズンを一括削除
	BulkDeleteSeasons(ctx context.Context, dollar_1 []pgtype.UUID) error
	CountSeasons(ctx context.Context) (int64, error)
	CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error)
	// 開発・テスト用: 全シーズンを削除
	DeleteAllSeasons(ctx context.Context) error
	DeleteSeason(ctx context.Context, seasonID pgtype.UUID) error
	GetActiveSeason(ctx context.Context) (Season, error)
	GetSeason(ctx context.Context, seasonID pgtype.UUID) (Season, error)
	ListSeasons(ctx context.Context) ([]Season, error)
	// シーズンのCRUD操作
	// Upsert: 存在する場合は更新、しない場合は挿入
	SaveSeason(ctx context.Context, arg SaveSeasonParams) (Season, error)
	// 既存のアクティブシーズンを無効化してから新しいシーズンを有効化
	SetActiveSeason(ctx context.Context, seasonID pgtype.UUID) error
	UpdateSeason(ctx context.Context, arg UpdateSeasonParams) (Season, error)
}

var _ Querier = (*Queries)(nil)
